language: perl
perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
notifications:
    #on_success: change
    on_success: always
    on_failure: always
    irc:
        channels:
            - "irc.perl.org#angel-PS1"
        template:
            - "github-keygen/%{branch}: %{message} %{build_url}"
    email: false
install:
    - cpanm --installdeps $(perl -e '$^V ge v5.10 && print "--with-develop"') . || { cat ~/.cpanm/build.log ; false ; }
    - cpanm App::Prove || { cat ~/.cpanm/build.log ; false ; }
script:
    - perl -c bin/github-keygen
    - prove xt/
    - perl -e 'exit !($^V lt v5.10)' || perl -c release.pl
